### ISSUE TITLE
Anarci Refactor

### ISSUE THREAD

**Issue by tmsincomb** [jwillis0720/sadie#40]
### Goal
- Speed increase 
- Replace high level HMMER implementation with low level using PyHMMER
- Keep Anarci numbering and region formatting.
---

### Data
  - [x] Create separated HMMs #41 
  - [x] create missing species from ALL.hmm to put into separated HMMs #73 

### Code
  - hmmer.py::HMMER
    - [x] build_hmm(stockholm: Path) -> None
    - [x] match test_cat to pyhmmer output for simple testing before moving on
    - [x] sadie.hmmer class api __init__
      - [x] species: replicate DataFrame[].func behavior for chimera behavior
    - [x] available_species property
    - [x] hmmsearch(seqs: str) -> pd.DataFrame
    - [x] numbering(hmm_aln, query_aln, query_seq: str, scheme: str, region: str, *args, **kwargs) -> pd.DataFrame
    - [x] hmmsearch(seqs: str) -> pd.DataFrame
   
### Afterburner Goals
  - [x] Squeeze ANARCI's formatting into a single class
    - The tools were squeezed into a single class, but the schemes and templates were left as scripts in the same level to reduce complexity of the refactor. A complete scheme rewrite does not seem practical, but examples, tests and docs are needed to increase community contributions. 
  - [x] replicate sadie API usage; any API changes should be a separate EPIC in itself. 
  ~~- [ ] look into streamlining muscle to remove stockholm input complexity~~
    - muscle not directly needed now since we can replicated behavior with known patterns for J and pre-aligned for V regions found in g3

### Testing
  - create new test_numbering
    - [x] ANARCI format testing (mostly to make sure any changes doesn't change it's output)
    - [x] build hmm test (whether or not it failed for each specie)
      - under test_g3 now since it is from src 
    - [x] query hmm test (has to match with existing output from test_anarci's single query)
      - currently within hmmer_translator.py that pulls models from g3 as priority than anarci src backup if species/chain does not exist in g3 

### Documentation Addition to README
  - ~~FlowChart input -> output~~
  - ~~simple hmm build from existing stockholm file~~
  - ~~simple query (sample seq should be importable)~~
    - ~~seq without ID only needed now~~

**Comment by tmsincomb** [comment]
pyhmmer hmmsearch runs test_cat in 3.5 ms and confirmed to have the same result as hmmscan. Hmmsearch is natively parallel by design so it might be faster to remove the multiprocessing overhead unless there is a certain number of sequence requests.

**Comment by jwillis0720** [comment]
@tmsincomb how is this going?

**Comment by tmsincomb** [comment]
The implementation is done; the readme now needs an API example for Renumbering and a flow chart to simplify how the backend works since its a bit more complex now. I should do that today so I can finally close this.

**Comment by tmsincomb** [comment]
Moving docs segment to another ticket
